Results: Show success, anomaly and failed counts on items
ooni/probe-multiplatform pull request #346
Opened 2024-12-10 18:45 UTC by sdsantos

Closes #340

2024-12-10 20:03 UTC, aanorbel requested changes

2024-12-10 20:03 UTC, aanorbel commented on composeApp/src/commonMain/kotlin/org/ooni/probe/data/models/ResultWithNetworkAndAggregates.kt
> +    val anomalyMeasurementsCount: Long,
Maybe something like this.
`measurementCount: MeasurementCount`

`
data class MeasurementCount(
    val done: Int,
    val failed: Int,
    val anomaly: Int
) {
    fun total() = done + failed + anomaly
}
`

2024-12-16 14:12 UTC, hellais commented on composeApp/src/commonMain/kotlin/org/ooni/probe/ui/results/ResultCell.kt
> +            descriptorName == "websites" || firstTest == TestType.WebConnectivity -> {
Is there some way we can make this view be general enough to not be so reliant on specific descriptor name and test_names?

2024-12-17 10:37 UTC, sdsantos commented on composeApp/src/commonMain/kotlin/org/ooni/probe/ui/results/ResultCell.kt
> +            descriptorName == "websites" || firstTest == TestType.WebConnectivity -> {
> Is there some way we can make this view be general enough to not be so reliant on specific descriptor name and test_names?

The requirement was to match the previous UI we had. Each one has a different name for anomalies, and we show the total websites tested. If it's OK to just use a more generic term for all of them, then we can simplify this.

Not sure how to deal with performance, which is showing quite different information. Should we just show if the tests didn't fail? Or start showing the performance summary like before?

<img width="586" alt="Screenshot 2024-12-17 at 10 37 17" src="https://github.com/user-attachments/assets/04b930e7-d9fc-48c7-af15-197de9c55a2d" />

2024-12-18 15:15 UTC, sdsantos commented
I made changes in the migrations in https://github.com/ooni/probe-multiplatform/pull/355. So let's merge that PR first, before merging this one, to avoid DB corruptions.

2024-12-18 15:48 UTC, aanorbel approved these changes
🐳

2025-01-06 07:30 UTC, merged