feat: add expired tag
ooni/probe-multiplatform pull request #359
Opened 2024-12-18 23:03 UTC by aanorbel

Closes https://github.com/ooni/probe-multiplatform/issues/356

2025-01-06 11:43 UTC, sdsantos requested changes

2025-01-06 11:43 UTC, sdsantos commented on composeApp/src/commonMain/kotlin/org/ooni/probe/domain/GetTestDescriptors.kt
> +    operator fun invoke(isExpired: Boolean? = null): Flow<List<Descriptor>> {
I don't think there's a case we'll want to get just the expired test descriptors with all the extra data this is fetching. So I think we could avoid having this argument here, so we don't need to set it as false in a lot of places.

2025-01-06 11:43 UTC, sdsantos commented on composeApp/src/commonMain/sqldelight/org/ooni/probe/data/TestDescriptor.sq
> +SELECT * FROM TestDescriptor WHERE (is_expired IS NULL OR is_expired = :isExpired) OR (:isExpired IS NULL);
Although we have a `is_expired` field inside the DB, we shouldn't. It's not a reliable way to know if the descriptor is actually expired, because it won't be updated every day. We only update it correctly if the user as enabled auto-update. Otherwise, it may be already expired, but the DB field is not updated.

Either we update the `is_expired` field for all descriptors consistently, or we should drop it from the DB and just use the expired date.

2025-01-06 16:00 UTC, aanorbel commented on composeApp/src/commonMain/kotlin/org/ooni/probe/domain/GetTestDescriptors.kt
> +    operator fun invoke(isExpired: Boolean? = null): Flow<List<Descriptor>> {
I think we need the argument. include expired tests or not to include expired tests

2025-01-07 12:48 UTC, sdsantos requested changes

2025-01-07 12:48 UTC, sdsantos commented on composeApp/src/commonMain/sqldelight/org/ooni/probe/data/TestDescriptor.sq
> +SELECT * FROM TestDescriptor WHERE (is_expired IS NULL OR (is_expired = :isExpired AND expiration_date > strftime('%s', 'now'))) OR (:isExpired IS NULL);
I believe this query is wrong. It should be ignoring the `is_expired` DB column and it doesn't work for returning the expired descriptors. Maybe try writing some tests for it?

I was expecting something like:
```
SELECT * FROM TestDescriptor WHERE
:isExpired IS NULL 
OR (:isExpired = 1 AND expiration_date < strftime('%s', 'now'))
OR (:isExpired = 0 AND expiration_date >= strftime('%s', 'now'))
```

2025-01-08 11:08 UTC, sdsantos requested changes
We also need to filter expired descriptors inside `GetAutoRunSpecification` at least.

2025-01-08 11:08 UTC, sdsantos commented on composeApp/src/commonMain/kotlin/org/ooni/probe/ui/run/RunViewModel.kt
> +}
The `Descriptor` model also has the `isExpired` field, so this `when` is not needed.

2025-01-08 14:38 UTC, sdsantos approved these changes

2025-01-08 15:18 UTC, merged